# Generated by Django 4.0.5 on 2023-02-04 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customer_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['email']},
        ),
        migrations.AlterModelOptions(
            name='gender',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='campaigntocustomer',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
