# Generated by Django 4.0.5 on 2023-02-05 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_campaigntocustomer_c2cid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailLog',
        ),
    ]
