# Generated by Django 4.0.5 on 2023-02-11 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_emaillog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='template',
        ),
    ]
