# Generated by Django 4.0.5 on 2023-02-11 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailcore', '0006_delete_camptotemplate'),
        ('core', '0008_remove_campaign_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emailcore.emailtemplate'),
        ),
    ]
