# Generated by Django 4.0.5 on 2023-02-14 17:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_campaign_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='campaign',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
