# Generated by Django 4.0.5 on 2023-02-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailcore', '0003_emaillimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillimit',
            name='limit',
            field=models.IntegerField(null=True),
        ),
    ]
