# Generated by Django 4.0.5 on 2023-02-11 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailcore', '0005_emailtemplate_camptotemplate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CampToTemplate',
        ),
    ]
