# Generated by Django 4.0.5 on 2023-02-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailcore', '0006_delete_camptotemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='file_name',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
