# Generated by Django 4.0.5 on 2023-02-14 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailcore', '0007_emailtemplate_file_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'ordering': ['-created']},
        ),
    ]
